services:
  backend:
    build: .
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tradoxus
      - REDIS_HOST=redis
      - REDIS_PORT=6381
    depends_on:
      - postgres
      - redis
    networks:
      - network
    volumes:
      - ./prisma/migrations:/app/prisma/migrations

  postgres:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tradoxus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6381"
    volumes:
      - redis-data:/data
    networks:
      - network
    command: redis-server --appendonly yes --protected-mode no --port 6381

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - network
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:
  prisma-migrations:

networks:
  network:
    driver: bridge
